### ISSUE TITLE
Does not compile with nvfortran 22.7

### ISSUE THREAD

**Issue by general-rishkin** [urbanjost/M_sort#2]
This is the error:
```
$ make F90=nvfortran nvfortran
nvfortran -Minform=inform -Mbackslash -traceback -c M_sort.f90
NVFORTRAN-S-0081-Illegal selector - KIND value must be non-negative  (M_sort.f90: 4122)
  0 inform,   0 warnings,   1 severes, 0 fatal for unique_real_real128
NVFORTRAN-S-0081-Illegal selector - KIND value must be non-negative  (M_sort.f90: 4195)
  0 inform,   0 warnings,   1 severes, 0 fatal for unique_complex_real128
NVFORTRAN-S-0081-Illegal selector - KIND value must be non-negative  (M_sort.f90: 5789)
NVFORTRAN-S-0081-Illegal selector - KIND value must be non-negative  (M_sort.f90: 5790)
  0 inform,   0 warnings,   2 severes, 0 fatal for sort_heap_real_real128
make: *** [Makefile:122: M_sort.o] Error 2
```

**Comment by urbanjost** [comment]
nvfortran does not support 128-bit float values.  Added cpp/fpp preprocessor directives to skip the 128-bit code so it should build with nvfortran.  Unfortunately I do not have a functioning version of nvfortran on my machine and have not been able to get it to work recently; so it is untested.  

Also changed the demos that use the array constructor syntax "[character(len=NN) :: 'a', 'ab', 'abcdef']" as nvfortran does not support that yet (from experience).  If you could give it a test that would be appreciated.

**Comment by urbanjost** [comment]
builds with nvfortran again; by using preprocessor directives to skip use of real128 variables.
