### ISSUE TITLE
Not working with fpm

### ISSUE THREAD

**Issue by general-rishkin** [urbanjost/M_sort#3]
This is the error:

```
fatal: your current branch 'main' does not have any commits yet
<ERROR>*cmd_run*:model error:Error while retrieving commit information
```

**Comment by urbanjost** [comment]
That does not appear to be related to this module but is just a normal git(1) error.  

Do "git commit -m init"   to create an initial git(1) commit.

**Comment by urbanjost** [comment]
To use remote dependencies you must do an initial commit in your project. That is a requirement of fpm and git that is true for all projects, and is not specific to just this one.
